# Generated by Django 4.2.4 on 2023-08-29 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_conversation_id_alter_conversationmessage_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={"ordering": ("created_at",)},
        ),
    ]
