# Generated by Django 4.2.3 on 2023-08-01 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
    ]
